#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http\://server1\:2181/eureka/,http\://server2\:2182/eureka/,http\://server3\:2183/eureka/

#zuul.SendErrorFilter.post.disable=true
zuul:
  max:
    host:
      connections: 500
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
  filter:
    pre:
      path: pre
    routing:
      path: route
    post:
      path: post
  ##serviceA的请求直接定位到具体的某台服务器
  routes:
    　vankeservice:
      path: /**
      url: http://10.0.73.17:16802

#endpoints:
#  restart:
#    enabled: true

spring:
  profiles:
    active: changeIp
  rabbitmq:
    host: xsfcjy.oicp.net
    port: 5672
    username: admin
    password: mypass
  zipkin:
    base-url: http://xsfcjy.oicp.net:9411
    

jdbc: 
  business:
    driverClassName: com.mysql.jdbc.Driver
    username: apigateway_root
    password: 123456
    #url: jdbc:mysql://xsfcjy.oicp.net:8607/sfxie_oa?characterEncoding=utf-8&amp;tinyInt1isBit=false
    #url: jdbc:mysql://mysql_scapigateway:3306/sc_apigateway?characterEncoding=utf-8&amp;tinyInt1isBit=false
    url: jdbc:mysql://xsfcjy.oicp.net:8066/sc_apigateway?characterEncoding=utf-8&amp;tinyInt1isBit=false
    
mybatis: 
  business:
    typeAliasesPackage: com.sfxie.sharecloud.apigateway.authentication.entity.business
    mapperLocations: classpath:/com/sfxie/sharecloud/apigateway/authentication/dao/business/sql/*.xml
    configLocation: config/mybatis/mybatis-config.xml
     
logging:
  path: ${logPath:D:/temp/logs}
  
constants:
  accessTimeout: ${accessTimeout:6000000} 
  
error:
  auth:
    emptyTime: 时间戳参数(ts)不能为空！
    emptyAppId: appId不能为空！
    emptyToken: token不能为空！
    timeout: ts已过期！
    timeFormat: 时间戳参数格式错误！
    denyInterface: 您没有此接口的访问权限！
    denyToken: token无效！
    emptyAccess: 您没有申请访问配置，请联系管理员！
    emptyInterface: 您还没有分配访问接口，请联系管理员！
    unableInterface: 此接口已过期！
    errorMethod: http接口请求方式错误，请以{0}方式请求接口！
code:
  auth:
    emptyTime: empty_time
    emptyAppId: empty_appId
    emptyToken: empty_token
    timeout: timeout
    timeFormat: timeFormat
    denyInterface: deny_interface
    denyToken: deny_token
    emptyAccess: empty_access
    emptyInterface: empty_interface
    unableInterface: unable_interface
    errorMethod: errorMethod